###
# 쿠키에 저장된 sessionId 값을 사용하여 모든 채팅방 조회
# 만약 sessionId 값이 없다면 빈 배열을 반환합니다.
GET http://192.168.0.25:8080/room/all


###
# 특정 채팅방의 대화 기록 조회
# {roomId} 부분에 실제 채팅방 ID를 넣어 요청합니다.
# 만약 존재하지 않는 roomId를 사용하면 빈 배열을 반환합니다.
# ex) /history/123e4567-e89b-12d3-a456-426614174000
GET http://192.168.0.25:8080/history/3887292d-fd65-4d65-8661-569589263d3d

###
# 채팅방의 이름 변경
# roomId 필드에 실제 채팅방 ID를 넣어 요청합니다.
# ex) "roomId" : 123e4567-e89b-12d3-a456-426614174000
# 동일한 sessionId 라면 roomName으로 채팅방 이름이 변경됩니다.
PUT http://192.168.0.25:8080/room
Content-Type: application/json

{
  "roomId": "123e4567-e89b-12d3-a456-426614174000",
  "roomName": "변경된 채팅방"
}

###
# 특정 채팅방 삭제
# {roomId} 부분에 실제 채팅방 ID를 넣어 요청합니다.
# 동일한 sessionId 라면 해당 채팅방이 삭제됩니다.
DELETE http://192.168.0.25:8080/room/{{roomId}}

###
# 챗봇 응답에 대한 평가 저장
# historySeq 필드에 평가할 대화 기록의 고유 번호를 넣어 요청합니다.
# point 필드에는 5점은 THUMBS_UP, 1점은 THUMBS_DOWN 으로 저장됩니다.
# comment 필드에는 평가에 대한 간단한 코멘트 기능이 필요할 시 넣어주면 저장됩니다.
POST http://192.168.0.25:8080/evaluation
Content-Type: application/json

{
  "historySeq": 0,
  "point": 0,
  "comment": ""
}

###
# 쿼리를 보내어 챗봇의 응답 받기
# chatRoomId는 대화가 이루어지는 채팅방의 ID입니다.
# 새로운 채팅방을 생성하려면 UUID 형식으로 임의의 값을 넣어주세요.
# 중복이 생길경우 기존 채팅방을 사용하지만, 만약 sessionId와 다르다면 오류가 발생합니다.
POST http://192.168.0.25:8080/chat/query
Content-Type: application/json

{
  "type": "USER",
  "content": "출산 휴가에 대해 설명해줘. 대략 몇일 받을 수 있어?",
  "chatRoomId": "123e4567-e89b-12d3-a456-426614174000"
}